name: Build Custom EMR Spark Image

on: push

env:
  ENV: stg
  AWS_ACCOUNT_ID: 296723344747
  AWS_REGION: ap-southeast-1
  DOCKER_VERSION: 5:20.10.13~3-0~ubuntu-focal

jobs:
  build-spark-image:
    runs-on: ubuntu-20.04
    steps:
      - run: "echo \"\U0001F389 The job was automatically triggered by a ${{ github.event_name }} event.\""
      - run: "echo \"\U0001F50E The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.\""
#      - name: Config AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          role-to-assume: $AWS_ACCOUNT_ID
#          aws-regio: $AWS_REGION
#          role-session-name: GithubActions
      - name: Set up Docker Build
        run: |
          sudo apt update
          sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt update
          apt list -a docker-ce
          sudo apt install docker-ce=$DOCKER_VERSION docker-ce-cli=$DOCKER_VERSION containerd.io
          sudo usermod -aG docker $USER
          docker container run hello-world